# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='toll',
            fields=[
                ('toll_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('toll_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('services', models.PositiveIntegerField()),
                ('car_price', models.PositiveIntegerField()),
                ('bike_price', models.PositiveIntegerField()),
                ('bus_price', models.PositiveIntegerField()),
                ('truck_price', models.PositiveIntegerField()),
            ],
        ),
    ]
